### ISSUE TITLE
broken link on about

### ISSUE THREAD

**Issue by koushiroue** [Diskordlit/FlashGuard#3]
sheeeesh

**Comment by ir4un** [comment]
The header buttons in the older branches are not useable, will look into a way and try to implement the buttons to link it to the section of the page soon

**Comment by koushiroue** [comment]
oh wow bemes, very cool, will look forward to this stuff

**Comment by koushiroue** [comment]
also the general consensus of closing the issue is that only if the issue is solved / found an alternative solution, you can repone the issue untill you finish solve it if yer want :p
